name: mobile_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.4
  supabase_flutter: ^2.5.6

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
