-- citiesテーブルを作成
CREATE TABLE public.cities (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    prefecture text not null,
    city text not null
);
-- prefectureとcityの組み合わせが重複しないようにユニーク制約を追加
ALTER TABLE public.cities ADD CONSTRAINT cities_prefecture_city_key UNIQUE (prefecture, city);

-- pinsテーブルを作成
CREATE TABLE public.pins (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    number text,
    address text,
    place_name text,
    lat double precision,
    long double precision,
    status smallint not null default 0,
    note text,
    city_id bigint not null references public.cities(id),
    updated_by uuid references auth.users(id)
);
