-- citiesテーブルを作成
create table public.cities (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    prefecture text not null,
    city text not null,
    constraint cities_prefecture_city_key unique (prefecture, city)
);

-- pinsテーブルを作成
create table public.pins (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    number text,
    address text,
    place_name text,
    lat double precision,
    long double precision,
    status smallint not null default 0,
    note text,
    city_id bigint not null,
    updated_by uuid,
    constraint pins_city_id_fkey foreign key (city_id) references public.cities (id),
    constraint pins_updated_by_fkey foreign key (updated_by) references auth.users (id)
);
