name: Daily Badge Calculation (Staging)

on:
  schedule:
    # 毎日日本時間0:05 (UTC 15:05)に実行
    - cron: '5 15 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  calculate-badges:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run badge calculation
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.STAGING_SUPABASE_SERVICE_ROLE_KEY }}
        run: npm run calculate-badges
        
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Staging] Badge Calculation Failed - ${new Date().toISOString().split('T')[0]}`,
              body: `The daily badge calculation workflow failed on staging. Please check the logs.\n\nWorkflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              labels: ['bug', 'automated', 'staging']
            });